### ISSUE TITLE
amber doesn't always reset terminal colors when exiting on Windows

### ISSUE THREAD

**Issue by Boscop** [dalance/amber#6]
![image](https://user-images.githubusercontent.com/535593/41402688-407aafd2-6fc3-11e8-8c3f-759b81e5101d.png)

**Comment by dalance** [comment]
@Boscop 
I fixed exiting without terminal reset.
Would you check with v0.4.4?

**Comment by Boscop** [comment]
Hm, it still happens:
![image](https://user-images.githubusercontent.com/535593/41407017-6e7a5bfc-6fce-11e8-8dd6-f0c13a955ad0.png)

**Comment by dalance** [comment]
The reset affected to stderr only.
I fixed with v0.4.5.

**Comment by Boscop** [comment]
Thanks ,it's fixed :)
